name: Build (non-kiosk)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [created, modified]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: |
        npm install
        npm run build
    - uses: actions/upload-artifact@master
      if: startsWith(github.ref, 'refs/tags/')
      with:
          name: dist
          path: ./dist
          retention-days: 1

  publish:
    needs: build 
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@master
        with:
          name: dist
      - name: Checkpoint
        run: |
          ls -alFh webshark
          cd webshark && sudo zip -r ../latest_raw.zip .
      - name: Upload Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            latest_raw.zip
